sudo: required
addons:
  chrome: stable
language: node_js
node_js:
  - node
dist: trusty
script:
  - bash ./scripts/deploy.sh
jobs:
  include:
  - stage: release
    node_js: lts/*
    deploy:
      provider: script
      skip_cleanup: true
      script:
      - npx semantic-release
